version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - gcc-net

  ruby:
    image: ruby2.4
    command: bash run.sh
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/app
      - ./run.sh:/var/www/app/run.sh
    environment:
      DB_USERNAME: root
      DB_HOST: mysql
      DB_PORT: "${MYSQL_PORT}"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      APP_NAME: "${APP_NAME}"
    # command: /var/www/app/run.sh
    # restart: always
    ports:
      - 3000:3000
    networks:
      - gcc-net

networks:
  gcc-net:
  

